'use strict';
/**
 * Build dist/catalogue.json, the one file Kosmos downloads, from the source files in this repo
 * (lib/source.js describes them), kosmos-builtin-roles.json and the portraits in avatars/. Moved here from the Kosmos repo's tools/catalogue/build.js
 * (joshualeestone/kosmos#4632); the roles and teams it writes are the shape Kosmos's
 * engine/catalogue.js reads.
 *
 *     node build.js            check everything, then write dist/catalogue.json and the portraits
 *     node build.js --check    check everything, write nothing (exit 1 on any problem)
 *
 * It refuses to write anything while a single problem remains. test/catalogue.test.js checks the
 * rules again against what build() returns.
 */
const fs = require('node:fs');
const path = require('node:path');

const crypto = require('node:crypto');
const source = require('./lib/source');

const OUT = path.join(__dirname, 'dist');
const NOTE = 'GENERATED by build.js in joshualeestone/kosmos-catalogue. Edit the source files there, not this file.';

// Words kept in capitals inside a sentence ("a PR specialist", "an HR policy writer").
const ACRONYMS = new Set(['CRM', 'HR', 'PR', 'QA', 'SEO', 'UX']);
// The house rule's spellings of the em dash: the character, the named and numeric entities
// (hex in either case), and the two source escapes. Written as escapes here, so this file has none.
const EM_DASHES = ['\u2014', '&mdash;', '&#8212;', '&#x2014;', '&#X2014;', '\\u2014', '\\u{2014}'];

function lowerLabel(label) {
  return label.split(/\s+/).map((w) => (ACRONYMS.has(w) ? w : w.toLowerCase())).join(' ');
}

/** "an" before a vowel sound: a vowel letter, or an acronym whose first letter's name starts
 *  with one (HR is "aitch-ar"). UX starts "you", so it takes "a". */
function articleFor(phrase) {
  const first = phrase.split(/\s+/)[0];
  if (ACRONYMS.has(first)) return 'AEFHILMNORSX'.includes(first[0]) ? 'an' : 'a';
  return 'aeiou'.includes(first[0].toLowerCase()) ? 'an' : 'a';
}

/** Greedy wrap at 76 columns, breaking only at spaces. */
function wrap(text, first = '', rest = '') {
  const out = [];
  let line = first;
  let empty = true;
  for (const word of String(text).split(/\s+/).filter(Boolean)) {
    const next = empty ? line + word : line + ' ' + word;
    if (!empty && next.length > 76) { out.push(line); line = rest + word; } else line = next;
    empty = false;
  }
  out.push(line);
  return out;
}

function sentences(text) {
  return String(text).split(/[.!?](?:\s|$)/).filter((s) => s.trim()).length;
}

function instructions(r) {
  const noun = lowerLabel(r.label);
  const lines = [`You are **{{NAME}}**, ${articleFor(noun)} ${noun}.`, ''];
  lines.push(...wrap(r.desc), '', '## Who you are', '', ...wrap(r.who), '', '## How you work', '');
  for (const b of r.how) lines.push(...wrap(b, '- ', '  '));
  return lines;
}

/** Text Kosmos would read as something other than words: a template marker other than {{NAME}}
 *  (the one create fills in), or an HTML comment, which is how Kosmos marks the blocks it manages
 *  inside an instruction file. */
function markerIn(value) {
  const blob = JSON.stringify(value);
  return /<!--/.test(blob) || /\{\{(?!NAME\}\})/.test(blob);
}

/** Why Kosmos would refuse this as an agent name (its engine/create.js nameProblem, ported), or null. */
function nameProblem(raw) {
  const name = String(raw);
  if (name !== name.trim() || /[^\S ]/.test(name)) return 'use single plain spaces, with nothing before or after';
  const slug = slugFor(name);
  if (slug.length < 2 || slug.length > 32) return 'use 2 to 32 characters';
  if (!/^[a-z0-9][a-z0-9_-]{1,31}$/.test(slug)) return 'use letters, numbers, hyphens and underscores, starting with a letter or number';
  if (/-discord$/.test(slug)) return 'names cannot end in -discord';
  if (slug === 'kosmos-connect') return 'that name is reserved';
  return null;
}

/** The machine name Kosmos makes from a name (engine/create.js slugFor): two names with the same
 *  one would be the same agent. */
function slugFor(raw) { return String(raw).trim().toLowerCase().replace(/[\s.]+/g, '-'); }

/** Any of the seven spellings anywhere in the value. JSON.stringify keeps the character itself and
 *  writes a typed backslash-u escape as \\u2014, which still contains the escape spelling. */
function emDashIn(value) {
  const blob = JSON.stringify(value);
  // Plus zero-padded numeric entities, the way tools/check-post-body.js matches them.
  return EM_DASHES.some((s) => blob.includes(s)) || /&#0*8212;|&#x0*2014;/i.test(blob);
}

/**
 * Compose the catalogue from the sources.
 * @param {{root?: string, rolesSource?: object, teamsSource?: object, serial?: number}} [src] a
 *   repo copy to read, or source objects to use instead of reading one (a test passes an edited
 *   copy); serial is written into the catalogue (0 when not given; main() passes the commit time)
 * @returns {{catalogue: object, text: string, problems: string[]}}
 */
function build(src = {}) {
  const root = src.root || source.ROOT;
  const read = source.read(root);
  const rs = src.rolesSource || read.rolesSource;
  const ts = src.teamsSource || read.teamsSource;
  const problems = read.problems.slice();
  if (typeof ts.TEAM_CAUTION !== 'string' || !ts.TEAM_CAUTION) problems.push('settings.json: teamCaution is missing');
  if (typeof ts.AVATAR_STYLE !== 'string' || !ts.AVATAR_STYLE) problems.push('settings.json: avatarStyle is missing');
  // Kosmos's own roles: a team member may name one, and a catalogue role must not reuse a key.
  const kosmos = readBuiltin(root, problems);
  const builtin = new Set(kosmos.all);        // no catalogue key may reuse one
  const pickable = new Set(kosmos.menu);      // a team member may use one (never own or setup)
  const groups = rs.GROUP_ORDER;
  if (emDashIn(groups)) problems.push('groups.json: em dash in a group name');
  for (const g of kosmos.groups) {
    if (!groups.includes(g)) problems.push(`groups.json: Kosmos's built-in roles sit in the group ${JSON.stringify(g)}, so it must stay (even with no catalogue role in it)`);
  }
  const roles = [];
  const seen = new Set();
  for (const r of rs.roles) {
    const k = r.key;
    if (!KEY_RE.test(String(k))) problems.push(`role key ${JSON.stringify(k)} must be lowercase words joined by hyphens`);
    if (seen.has(k)) problems.push('duplicate role key ' + k);
    if (builtin.has(k)) problems.push(`${k}: Kosmos already has a built-in role with this key`);
    seen.add(k);
    if (!groups.includes(r.group)) problems.push(`${k}: unknown group ${r.group}`);
    const n = sentences(r.who);
    if (n < 3 || n > 6) problems.push(`${k}: character is ${n} sentences, three to six is the rule`);
    if (!Array.isArray(r.how) || r.how.length !== 3) problems.push(`${k}: How you work needs exactly three bullets`);
    if (!r.first || r.first.length <= 10) problems.push(`${k}: first action too short`);
    const entry = { key: k, group: r.group, label: r.label, blurb: r.blurb, firstAction: r.first };
    if (r.caution) entry.caution = r.caution;
    entry.instructions = instructions(r);
    // The product's wrapper keeps a `code span` on one line; this one does not, so refuse text
    // whose wrap would split one (an odd count of backticks on a line) rather than ship it broken.
    if (entry.instructions.some((l) => (l.match(/`/g) || []).length % 2)) problems.push(`${k}: a code span is split across lines`);
    if (emDashIn(entry)) problems.push(`${k}: em dash`);
    if (markerIn(entry)) problems.push(`${k}: a template marker other than {{NAME}}, or an HTML comment`);
    roles.push(entry);
  }
  const teams = [];
  const seenNames = new Map();
  const seenRanks = new Map();
  const avatarIds = new Map();
  for (const t of ts.teams) {
    // Keys and slots name files (avatars/<key>-<slot>.webp), so they are checked before any use.
    if (!KEY_RE.test(String(t.key))) { problems.push(`team key ${JSON.stringify(t.key)} must be lowercase words joined by hyphens`); continue; }
    if (!Array.isArray(t.members) || !t.members.every((m) => m && typeof m === 'object')) { problems.push(`${t.key}: members must be a list of people`); continue; }
    const badSlot = t.members.find((m) => !KEY_RE.test(String(m.slot)));
    if (badSlot) { problems.push(`${t.key}: slot ${JSON.stringify(badSlot.slot)} must be lowercase words joined by hyphens`); continue; }
    const AVATAR = ['apparentAge', 'presentation', 'heritage', 'hair', 'attire', 'expression'];
    const incomplete = t.members.find((m) => !isText(m.name) || !isText(m.title) || !isText(m.role)
      || !Array.isArray(m.focus) || !m.focus.every(isText)
      || !m.avatar || typeof m.avatar !== 'object' || !AVATAR.every((f) => isText(m.avatar[f])));
    if (incomplete) {
      problems.push(`${t.key}/${incomplete.slot}: needs a name, title, role, focus (a list of lines) and an avatar with ${AVATAR.join(', ')}`);
      continue;
    }
    for (const m of t.members) {
      const id = `${t.key}-${m.slot}`;
      if (avatarIds.has(id)) problems.push(`portrait id ${id} is used by ${avatarIds.get(id)} and ${t.key}`);
      avatarIds.set(id, t.key);
    }
    for (const m of t.members) {
      const bad = nameProblem(m.name);
      if (bad) problems.push(`${t.key}/${m.slot}: Kosmos would refuse the name ${JSON.stringify(m.name)}: ${bad}`);
      // Compared as Kosmos compares agents: by machine name, so "Mary Jo" and "mary.jo" collide.
      const slug = slugFor(m.name);
      if (seenNames.has(slug)) problems.push(`suggested name ${m.name} is used by ${seenNames.get(slug)} and ${t.key}`);
      seenNames.set(slug, t.key);
    }
    if (!['business', 'personal'].includes(t.kind)) problems.push(`${t.key}: kind must be business or personal`);
    if (!Number.isInteger(t.rank) || t.rank < 1) problems.push(`${t.key}: rank must be a whole number from 1`);
    const rk = t.kind + '#' + t.rank;
    if (seenRanks.has(rk)) problems.push(`${seenRanks.get(rk)} and ${t.key} share ${t.kind} rank ${t.rank}`);
    seenRanks.set(rk, t.key);
    const leads = t.members.filter((m) => m.slot === 'lead').length;
    if (leads !== 1) problems.push(`${t.key}: needs exactly one lead slot, has ${leads}`);
    const reports = t.members.length - leads;
    if (reports < 4 || reports > 5) problems.push(`${t.key}: needs 4 or 5 reports, has ${reports}`);
    if (new Set(t.members.map((m) => m.slot)).size !== t.members.length) problems.push(`${t.key}: a slot repeats`);
    for (const m of t.members) {
      if (!seen.has(m.role) && !pickable.has(m.role)) problems.push(`${t.key}/${m.slot}: role ${JSON.stringify(m.role)} is neither a catalogue role nor one Kosmos has built in`);
    }
    const members = t.members.map((m) => {
      const id = `${t.key}-${m.slot}`;
      // The portrait, when one has been made: avatars/<id>.webp, published beside catalogue.json.
      const image = portrait(root, id, problems);
      const a = { ...m.avatar, id, image: image && image.path, imageSha256: image && image.sha256 };
      const title = lowerLabel(m.title);
      const pronoun = { woman: 'her', man: 'his' }[a.presentation] || 'their';
      a.prompt = `${ts.AVATAR_STYLE} Subject: ${articleFor(a.presentation)} ${a.presentation} in ${pronoun} ${a.apparentAge}, `
        + `of ${a.heritage} heritage. Hair: ${a.hair}. Clothing: ${a.attire}. Expression: ${a.expression}. `
        + `Role: works as ${articleFor(title)} ${title}.`;
      return { slot: m.slot, role: m.role, title: m.title, name: m.name,
        reportsTo: m.slot === 'lead' ? null : 'lead', focus: m.focus, avatar: a };
    });
    if (![t.label, t.blurb, t.purpose].every(isText) || !t.project || !isText(t.project.name) || !isText(t.project.goal)) {
      problems.push(`${t.key}: needs a label, blurb, purpose, and a project with a name and goal`);
    }
    const entry = { key: t.key, kind: t.kind, rank: t.rank, label: t.label, blurb: t.blurb,
      purpose: t.purpose, caution: ts.TEAM_CAUTION, project: t.project, members };
    // Team text is what the Team screen shows (#4556, #4557), so it gets the same guard.
    if (emDashIn(entry)) problems.push(`${t.key}: em dash`);
    if (markerIn(entry)) problems.push(`${t.key}: a template marker, or an HTML comment`);
    teams.push(entry);
  }
  // serial: which build this is, inside the signed bytes, so Kosmos can refuse an older catalogue
  // than the one it already holds (a replayed old file carries a valid signature too).
  // A portrait no member names is a misspelt file name (and on a case-insensitive disk it would
  // match locally and not in CI), so it is reported rather than quietly left out.
  try {
    if (fs.lstatSync(path.join(root, 'avatars')).isDirectory()) {
      for (const f of fs.readdirSync(path.join(root, 'avatars'))) {
        if (f.endsWith('.webp') && !avatarIds.has(f.slice(0, -5))) problems.push(`avatars/${f}: no team member has the id ${f.slice(0, -5)}`);
      }
    }
  } catch { /* no avatars folder: nothing to match */ }
  // kosmosRoles: the built-in keys this catalogue was checked against, so Kosmos's own tests can
  // tell when its roles and this list have drifted apart.
  const catalogue = { generated: NOTE, version: 2, serial: src.serial || 0, kosmosRoles: kosmos.all.slice().sort(),
    groups, roles, avatarStyle: ts.AVATAR_STYLE, teams };
  return { catalogue, text: JSON.stringify(catalogue, null, 2) + '\n', problems };
}

const KEY_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const isText = (v) => typeof v === 'string' && v.length > 0;
// A commit time this far past the clock is a wrong clock, not a build: signed as the serial, it
// would make Kosmos refuse every real catalogue until the clock caught up.
const FUTURE_SKEW_S = 3600;
const MAX_PORTRAIT_BYTES = 512 * 1024;

function sha256(bytes) { return crypto.createHash('sha256').update(bytes).digest('hex'); }

function readBuiltin(root, problems) {
  try {
    const b = JSON.parse(fs.readFileSync(path.join(root, 'kosmos-builtin-roles.json'), 'utf8'));
    const ok = (l) => Array.isArray(l) && l.every((k) => typeof k === 'string');
    if (ok(b.roles) && ok(b.hidden) && ok(b.groups)) return { menu: b.roles, all: b.roles.concat(b.hidden), groups: b.groups };
  } catch { /* reported below */ }
  problems.push('kosmos-builtin-roles.json: must hold "roles" (menu), "hidden" and "groups" lists');
  return { menu: [], all: [], groups: [] };
}

/**
 * The portrait for one member, when one has been made: avatars/<id>.webp, a regular file (a
 * symlink is refused, so nothing outside the repo is published). Its sha256 goes into the signed
 * catalogue, so Kosmos can check the image it downloads beside it.
 * @returns {{path: string, sha256: string}|null}
 */
function portrait(root, id, problems) {
  const rel = `avatars/${id}.webp`;
  let dir;
  try { dir = fs.lstatSync(path.join(root, 'avatars')); } catch { return null; }
  if (!dir.isDirectory()) { problems.push('avatars/: must be a folder in this repo, not a link'); return null; }
  let st;
  try { st = fs.lstatSync(path.join(root, rel)); } catch { return null; }
  if (!st.isFile()) { problems.push(`${rel}: must be a regular file, not a link or a folder`); return null; }
  if (st.size > MAX_PORTRAIT_BYTES) { problems.push(`${rel}: larger than ${MAX_PORTRAIT_BYTES} bytes`); return null; }
  const bytes = fs.readFileSync(path.join(root, rel));
  // A WebP file is a RIFF container whose form type is WEBP.
  if (bytes.subarray(0, 4).toString('latin1') !== 'RIFF' || bytes.subarray(8, 12).toString('latin1') !== 'WEBP') {
    problems.push(`${rel}: is not a WebP image`);
    return null;
  }
  return { path: rel, sha256: sha256(bytes) };
}

/** The environment without GIT_DIR and GIT_WORK_TREE, which a git hook exports: they would point
 *  git at the hook's repo instead of the one named with -C. */
function withoutGitDir() {
  const env = { ...process.env };
  delete env.GIT_DIR;
  delete env.GIT_WORK_TREE;
  return env;
}

/** The commit time of HEAD in seconds. Not guaranteed to grow (a commit made on a slow clock),
 *  so main() also keeps the serial above the one already published. */
function commitTime(root) {
  try {
    const out = require('node:child_process').execFileSync('git', ['-C', root, 'log', '-1', '--format=%ct', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'], env: withoutGitDir() });
    const n = Number(out.trim());
    return Number.isInteger(n) && n > 0 ? n : 0;
  } catch { return 0; }
}

/** Why a serial cannot be signed, or null. */
function serialProblem(serial, nowS = Math.floor(Date.now() / 1000)) {
  if (!Number.isInteger(serial) || serial < 1) return 'no serial: build.js must run in a git checkout with a commit';
  if (serial > nowS + FUTURE_SKEW_S) return `the commit time ${serial} is later than now (${nowS}); a wrong clock made that commit`;
  return null;
}

/**
 * @param {string[]} argv
 * @param {{root?: string, out?: string, nowS?: number, previousSerial?: number}} [opts] a repo copy and
 *   output folder (tests), and the published serial the new one must exceed
 */
function main(argv, opts = {}) {
  const root = opts.root || source.ROOT;
  const out = opts.out || OUT;
  // publish.yml passes the published catalogue's serial; a new one must be above it, or every
  // Kosmos holding the published one would refuse it.
  const given = opts.previousSerial ?? process.env.CATALOGUE_PREVIOUS_SERIAL ?? '';
  const previous = given === '' ? 0 : Number(given);
  if (!Number.isInteger(previous) || previous < 0) {
    process.stderr.write(`refused: the published serial ${JSON.stringify(String(given))} is not a whole number\n`);
    return 1;
  }
  const commit = commitTime(root);
  const serial = commit ? Math.max(commit, previous + 1) : 0;
  const { catalogue, text, problems } = build({ root, serial });
  const sp = serialProblem(serial, opts.nowS);
  if (sp) problems.push(sp);
  if (problems.length) {
    process.stderr.write('refused:\n  ' + problems.join('\n  ') + '\n');
    return 1;
  }
  const members = catalogue.teams.reduce((s, t) => s + t.members.length, 0);
  const summary = `${catalogue.roles.length} roles and ${catalogue.teams.length} teams (${members} members)`;
  if (argv.includes('--check')) { process.stdout.write(`ok: ${summary}\n`); return 0; }
  // Start from an empty folder, so no signature or portrait from an earlier build rides along.
  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(out, 'catalogue.json'), text);
  // The portraits the catalogue names, published beside it under the same relative paths.
  const images = catalogue.teams.flatMap((t) => t.members.map((m) => m.avatar.image)).filter(Boolean);
  for (const rel of images) {
    fs.mkdirSync(path.dirname(path.join(out, rel)), { recursive: true });
    fs.copyFileSync(path.join(root, rel), path.join(out, rel));
  }
  process.stdout.write(`wrote catalogue.json: ${summary}\n`);
  return 0;
}

module.exports = { build, main, sha256, serialProblem, nameProblem, slugFor, EM_DASHES };
if (require.main === module) process.exitCode = main(process.argv.slice(2));
