'use strict';
/**
 * Build dist/catalogue.json, the one file Kosmos downloads, from the source files in this repo
 * (lib/source.js describes them). Moved here from the Kosmos repo's tools/catalogue/build.js
 * (joshualeestone/kosmos#4632); the roles and teams it writes are the shape Kosmos's
 * engine/catalogue.js reads.
 *
 *     node build.js            check everything, then write dist/catalogue.json and the portraits
 *     node build.js --check    check everything, write nothing (exit 1 on any problem)
 *
 * It refuses to write anything while a single problem remains. test/catalogue.test.js checks the
 * rules again against the built file.
 */
const fs = require('node:fs');
const path = require('node:path');

const crypto = require('node:crypto');
const source = require('./lib/source');

const OUT = path.join(__dirname, 'dist');
const NOTE = 'GENERATED by build.js in joshualeestone/kosmos-catalogue. Edit the source files there, not this file.';

// Words kept in capitals inside a sentence ("a PR specialist", "an HR policy writer").
const ACRONYMS = new Set(['CRM', 'HR', 'PR', 'QA', 'SEO', 'UX']);
// The house rule's spellings of the em dash: the character, the named and numeric entities
// (hex in either case), and the two source escapes. Written as escapes here, so this file has none.
const EM_DASHES = ['\u2014', '&mdash;', '&#8212;', '&#x2014;', '&#X2014;', '\\u2014', '\\u{2014}'];

function lowerLabel(label) {
  return label.split(/\s+/).map((w) => (ACRONYMS.has(w) ? w : w.toLowerCase())).join(' ');
}

/** "an" before a vowel sound: a vowel letter, or an acronym whose first letter's name starts
 *  with one (HR is "aitch-ar"). UX starts "you", so it takes "a". */
function articleFor(phrase) {
  const first = phrase.split(/\s+/)[0];
  if (ACRONYMS.has(first)) return 'AEFHILMNORSX'.includes(first[0]) ? 'an' : 'a';
  return 'aeiou'.includes(first[0].toLowerCase()) ? 'an' : 'a';
}

/** Greedy wrap at 76 columns, breaking only at spaces. */
function wrap(text, first = '', rest = '') {
  const out = [];
  let line = first;
  let empty = true;
  for (const word of String(text).split(/\s+/).filter(Boolean)) {
    const next = empty ? line + word : line + ' ' + word;
    if (!empty && next.length > 76) { out.push(line); line = rest + word; } else line = next;
    empty = false;
  }
  out.push(line);
  return out;
}

function sentences(text) {
  return String(text).split(/[.!?](?:\s|$)/).filter((s) => s.trim()).length;
}

function instructions(r) {
  const noun = lowerLabel(r.label);
  const lines = [`You are **{{NAME}}**, ${articleFor(noun)} ${noun}.`, ''];
  lines.push(...wrap(r.desc), '', '## Who you are', '', ...wrap(r.who), '', '## How you work', '');
  for (const b of r.how) lines.push(...wrap(b, '- ', '  '));
  return lines;
}

/** Any of the five spellings anywhere in the value. JSON.stringify keeps the character itself and
 *  writes a typed backslash-u escape as \\u2014, which still contains the escape spelling. */
function emDashIn(value) {
  const blob = JSON.stringify(value);
  // Plus zero-padded numeric entities, the way tools/check-post-body.js matches them.
  return EM_DASHES.some((s) => blob.includes(s)) || /&#0*8212;|&#x0*2014;/i.test(blob);
}

/**
 * Compose the catalogue from the sources.
 * @param {{root?: string, rolesSource?: object, teamsSource?: object, serial?: number}} [src] a
 *   repo copy to read, or source objects to use instead of reading one (a test passes an edited
 *   copy); serial is written into the catalogue (0 when not given; main() passes the commit time)
 * @returns {{catalogue: object, text: string, problems: string[]}}
 */
function build(src = {}) {
  const root = src.root || source.ROOT;
  const read = source.read(root);
  const rs = src.rolesSource || read.rolesSource;
  const ts = src.teamsSource || read.teamsSource;
  const problems = read.problems.slice();
  if (typeof ts.TEAM_CAUTION !== 'string' || !ts.TEAM_CAUTION) problems.push('settings.json: teamCaution is missing');
  if (typeof ts.AVATAR_STYLE !== 'string' || !ts.AVATAR_STYLE) problems.push('settings.json: avatarStyle is missing');
  // Kosmos's own roles: a team member may name one, and a catalogue role must not reuse a key.
  const builtin = new Set(readBuiltin(root, problems));
  const groups = rs.GROUP_ORDER;
  const roles = [];
  const seen = new Set();
  for (const r of rs.roles) {
    const k = r.key;
    if (seen.has(k)) problems.push('duplicate role key ' + k);
    if (builtin.has(k)) problems.push(`${k}: Kosmos already has a built-in role with this key`);
    seen.add(k);
    if (!groups.includes(r.group)) problems.push(`${k}: unknown group ${r.group}`);
    const n = sentences(r.who);
    if (n < 3 || n > 6) problems.push(`${k}: character is ${n} sentences, three to six is the rule`);
    if (!Array.isArray(r.how) || r.how.length !== 3) problems.push(`${k}: How you work needs exactly three bullets`);
    if (!r.first || r.first.length <= 10) problems.push(`${k}: first action too short`);
    const entry = { key: k, group: r.group, label: r.label, blurb: r.blurb, firstAction: r.first };
    if (r.caution) entry.caution = r.caution;
    entry.instructions = instructions(r);
    // The product's wrapper keeps a `code span` on one line; this one does not, so refuse text
    // whose wrap would split one (an odd count of backticks on a line) rather than ship it broken.
    if (entry.instructions.some((l) => (l.match(/`/g) || []).length % 2)) problems.push(`${k}: a code span is split across lines`);
    if (emDashIn(entry)) problems.push(`${k}: em dash`);
    roles.push(entry);
  }
  const teams = [];
  const seenNames = new Map();
  const seenRanks = new Map();
  for (const t of ts.teams) {
    for (const m of t.members) {
      const lower = m.name.toLowerCase();
      if (seenNames.has(lower)) problems.push(`suggested name ${m.name} is used by ${seenNames.get(lower)} and ${t.key}`);
      seenNames.set(lower, t.key);
    }
    if (!['business', 'personal'].includes(t.kind)) problems.push(`${t.key}: kind must be business or personal`);
    if (!Number.isInteger(t.rank) || t.rank < 1) problems.push(`${t.key}: rank must be a whole number from 1`);
    const rk = t.kind + '#' + t.rank;
    if (seenRanks.has(rk)) problems.push(`${seenRanks.get(rk)} and ${t.key} share ${t.kind} rank ${t.rank}`);
    seenRanks.set(rk, t.key);
    const leads = t.members.filter((m) => m.slot === 'lead').length;
    if (leads !== 1) problems.push(`${t.key}: needs exactly one lead slot, has ${leads}`);
    const reports = t.members.length - leads;
    if (reports < 4 || reports > 5) problems.push(`${t.key}: needs 4 or 5 reports, has ${reports}`);
    if (new Set(t.members.map((m) => m.slot)).size !== t.members.length) problems.push(`${t.key}: a slot repeats`);
    for (const m of t.members) {
      if (!Array.isArray(m.focus)) problems.push(`${t.key}/${m.slot}: focus must be a list`);
      if (!seen.has(m.role) && !builtin.has(m.role)) problems.push(`${t.key}/${m.slot}: role ${JSON.stringify(m.role)} is neither a catalogue role nor one Kosmos has built in`);
    }
    const members = t.members.map((m) => {
      const id = `${t.key}-${m.slot}`;
      // The portrait, when one has been made: avatars/<id>.webp, published beside catalogue.json.
      const image = portrait(root, id, problems);
      const a = { ...m.avatar, id, image: image && image.path, imageSha256: image && image.sha256 };
      const title = lowerLabel(m.title);
      const pronoun = { woman: 'her', man: 'his' }[a.presentation] || 'their';
      a.prompt = `${ts.AVATAR_STYLE} Subject: ${articleFor(a.presentation)} ${a.presentation} in ${pronoun} ${a.apparentAge}, `
        + `of ${a.heritage} heritage. Hair: ${a.hair}. Clothing: ${a.attire}. Expression: ${a.expression}. `
        + `Role: works as ${articleFor(title)} ${title}.`;
      return { slot: m.slot, role: m.role, title: m.title, name: m.name,
        reportsTo: m.slot === 'lead' ? null : 'lead', focus: m.focus, avatar: a };
    });
    const entry = { key: t.key, kind: t.kind, rank: t.rank, label: t.label, blurb: t.blurb,
      purpose: t.purpose, caution: ts.TEAM_CAUTION, project: t.project, members };
    // Team text is what the Team screen shows (#4556, #4557), so it gets the same guard.
    if (emDashIn(entry)) problems.push(`${t.key}: em dash`);
    teams.push(entry);
  }
  // serial: which build this is, inside the signed bytes, so Kosmos can refuse an older catalogue
  // than the one it already holds (a replayed old file carries a valid signature too).
  const catalogue = { generated: NOTE, version: 1, serial: src.serial || 0, groups, roles, avatarStyle: ts.AVATAR_STYLE, teams };
  return { catalogue, text: JSON.stringify(catalogue, null, 2) + '\n', problems };
}

function sha256(bytes) { return crypto.createHash('sha256').update(bytes).digest('hex'); }

function readBuiltin(root, problems) {
  try {
    const list = JSON.parse(fs.readFileSync(path.join(root, 'kosmos-builtin-roles.json'), 'utf8')).roles;
    if (Array.isArray(list) && list.every((k) => typeof k === 'string')) return list;
  } catch { /* reported below */ }
  problems.push('kosmos-builtin-roles.json: must hold a "roles" list of role keys');
  return [];
}

/**
 * The portrait for one member, when one has been made: avatars/<id>.webp, a regular file (a
 * symlink is refused, so nothing outside the repo is published). Its sha256 goes into the signed
 * catalogue, so Kosmos can check the image it downloads beside it.
 * @returns {{path: string, sha256: string}|null}
 */
function portrait(root, id, problems) {
  const rel = `avatars/${id}.webp`;
  let st;
  try { st = fs.lstatSync(path.join(root, rel)); } catch { return null; }
  if (!st.isFile()) { problems.push(`${rel}: must be a regular file, not a link or a folder`); return null; }
  return { path: rel, sha256: sha256(fs.readFileSync(path.join(root, rel))) };
}

/** The commit time of HEAD in seconds, which only grows as main moves: the catalogue's serial. */
function commitTime(root) {
  try {
    const out = require('node:child_process').execFileSync('git', ['-C', root, 'log', '-1', '--format=%ct', 'HEAD'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    const n = Number(out.trim());
    return Number.isInteger(n) && n > 0 ? n : 0;
  } catch { return 0; }
}

function main(argv) {
  const serial = commitTime(source.ROOT);
  const { catalogue, text, problems } = build({ serial });
  if (!serial) problems.push('no serial: build.js must run in a git checkout with a commit');
  if (problems.length) {
    process.stderr.write('refused:\n  ' + problems.join('\n  ') + '\n');
    return 1;
  }
  const members = catalogue.teams.reduce((s, t) => s + t.members.length, 0);
  const summary = `${catalogue.roles.length} roles and ${catalogue.teams.length} teams (${members} members)`;
  if (argv.includes('--check')) { process.stdout.write(`ok: ${summary}\n`); return 0; }
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'catalogue.json'), text);
  // The portraits the catalogue names, published beside it under the same relative paths.
  const images = catalogue.teams.flatMap((t) => t.members.map((m) => m.avatar.image)).filter(Boolean);
  for (const rel of images) {
    fs.mkdirSync(path.dirname(path.join(OUT, rel)), { recursive: true });
    fs.copyFileSync(path.join(source.ROOT, rel), path.join(OUT, rel));
  }
  process.stdout.write(`wrote dist/catalogue.json: ${summary}\n`);
  return 0;
}

module.exports = { build, sha256, EM_DASHES };
if (require.main === module) process.exitCode = main(process.argv.slice(2));
